Test

diff --git a/.github/workflows/phpcs.yml b/.github/workflows/phpcs.yml
--- a/.github/workflows/phpcs.yml
+++ b/.github/workflows/phpcs.yml
@@ -46,13 +46,13 @@ jobs:
                 -level="${INPUT_LEVEL:-warning}" < "${GIT_DIFF}" || REVIEWDOG_EXIT_CODE=$?
             fi
           fi
-          phpcs --report-checkstyle="${PHPCS_JSON}" "${GITHUB_WORKSPACE}" || PHPCS_EXIT_CODE=$?
+          # phpcs --report-checkstyle="${PHPCS_JSON}" "${GITHUB_WORKSPACE}" || PHPCS_EXIT_CODE=$?
 
-          cat "${PHPCS_JSON}" \
-            | reviewdog -f="checkstyle" \
-                -name="${INPUT_TOOL_NAME:-reviewdog-suggester}" \
-                -reporter="github-pr-review" \
-                -filter-mode="${INPUT_FILTER_MODE:-diff_context}" \
-                -fail-on-error="${INPUT_FAIL_ON_ERROR:-true}" \
-                -level="${INPUT_LEVEL:-warning}"
+          # cat "${PHPCS_JSON}" \
+          #  | reviewdog -f="checkstyle" \
+          #      -name="${INPUT_TOOL_NAME:-reviewdog-suggester}" \
+          #      -reporter="github-pr-review" \
+          #      -filter-mode="${INPUT_FILTER_MODE:-diff_context}" \
+          #      -fail-on-error="${INPUT_FAIL_ON_ERROR:-true}" \
+          #      -level="${INPUT_LEVEL:-warning}"
           git stash -u && git stash drop
